-d C:\Users\niner\Desktop\servo\impl\gwsynthesis\servo.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst C:\Users\niner\Desktop\servo\src\servo.cst
-cfg C:\Users\niner\Desktop\servo\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
