-d F:\Radar_VHDL\gowin\ul\impl\gwsynthesis\ul.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst F:\Radar_VHDL\gowin\ul\src\ul.cst
-cfg F:\Radar_VHDL\gowin\ul\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
